### PR TITLE
Mint-X-Dark: Initial creation

### PR DESCRIPTION
**Pull request by Goodevil95**
Dark theme in Mint-X style.

### CODE REVIEW

**Comment by NikoKrause** [comment]
Don't use html in the info.json description:
```
"description": "Dark theme in Mint-X style"
```
is enough

**Comment by Goodevil95** [comment]
Sorry, I didn't know this. I just copied it from [here](https://github.com/linuxmint/cinnamon-spices-themes/blob/master/ChromeOS/info.json) :)

**Comment by NikoKrause** [comment]
It's a new change for Cinnamon 3.6 
https://github.com/linuxmint/cinnamon-spices-themes/issues/221#issuecomment-330680181

**Comment by Goodevil95** [comment]
Thank you for information! I removed HTML code. Could you accept my theme?

**Comment by NikoKrause** [comment]
I can't merge themes. But a Dark version of Mint-X seems pretty cool.

**Comment by Goodevil95** [comment]
Thanks :)

**Pull request merged**
