### PR TITLE
Thunderbolt: Deleted directory Cinnamon + create directory cinnamon

### PR DESCRIPTION
**Pull request by Radek71**

### CODE REVIEW

**Comment by JosephMcc** [comment]
Could you do me a favor and squash all of this into a single commit and provide a commit message that includes the name. Something like: Thunderbolt: Delete directory Cinnamon + create directory cinnamon

It helps to keep a reasonable git history since multiple devs and projects are involved.

**Comment by Radek71** [comment]
@JosephMcc,
sorry for troubles with my commits - I am new github user and still discovering how it works. I have added the correct name/format for this pull request. But true is that I do not know how to squash more commits into a single one - I have to find and learn "how to".
Thank you for your patience.

**Comment by JosephMcc** [comment]
No problem. Git is nice but it does take a bit to get the hang of. Here is a quick example of how to squash your commits: https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

You can also follow the link at the bottom of that page to find more info.

**Comment by brownsr** [comment]
@Radek71   git rebase -i HEAD~n  where n is the number of commits.  That will bring up a screen showing a list of commits.  By default each line starts 'pick'.  Leave the first one alone, and then change 'pick' to 's' for all the subsequent ones, then exit (ctrl -X usually), saying Y and agreeing with the filenames offered when git prompts you.  Then the comment screen will show. You can cut down the size of the comment by putting # at the beginning of lines you don't want.  Then exit in the same way as before.  Hopefully git will then tell you it has all worked.  Then you have to push as usual, except you will have to add a -f for force.

If this goes wrong or you find you are struggling, then reply back, and I'll put a commit through - I ended up doing one in parallel with you, but closed mine when I saw that you had done one, as the original author has preference ;) But I can easily reopen and submit it if you want.  Simon.

**Comment by NikoKrause** [comment]
Make a backup before doing that!

**Comment by Radek71** [comment]
@brownsr,
Thanks for your support. I have tried the recommended steps, but unfortunately something goes wrong. So I mean the best way to solve it will be to close my PR and I would like to ask you for reopen your. 
Thanks again. Radek

**Comment by NikoKrause** [comment]
@Radek71 
One problem I had, when I started rebase was the editor, which was used by git.
Try the following steps.

* I would suggest that you configure git to use your favorite editor. Open Terminal and type:
`git config --global core.editor "xed"`
If you want to use the `xed` editor, else change `"xed"`to your favorite text editor.
* Then open a terminal in your git branch.
* Now this pull request has 31 commits. So type in `git rebase -i HEAD~31`. This should open an `xed` window, which looks like this:
```py
pick 2708032 Add files via upload
pick 23f73b3 Delete calendar-arrow-left.svg
pick a8f358e Delete calendar-arrow-right.svg
pick e54abbf Delete checkbox-off.svg
pick 7522202 Delete checkbox.svg
pick 2111568 Delete cinnamon.css
pick 0e6d45b Delete close-window.svg
pick f1fa5fc Delete close.svg
pick f6e92d2 Delete corner-ripple.png
pick 60d02cd Delete menu-symbolic.svg
pick 349c790 Delete metadata.json
pick 134c0e2 Delete overview-hover.png
pick 924e09d Delete overview.png
pick 84db6a1 Delete panel-button-highlight-narrow.svg
pick c256f3a Delete panel-button-highlight-wide-round.svg
pick 4990e00 Delete panel-button-highlight-wide-round2.svg
pick 17460a9 Delete panel-button-highlight-wide.svg
pick 6e29345 Delete plus.svg
pick a71556d Delete preview.png
pick 0f9ecb2 Delete process-working.svg
pick 44ef09c Delete radiobutton-off.svg
pick 3a099c8 Delete radiobutton.svg
pick ae15420 Delete thumbnail.png
pick 461d35b Delete toggle-off-intl.svg
pick 0593cb2 Delete toggle-off-us.svg
pick 5ac92a6 Delete toggle-on-intl.svg
pick f5f4dbc Delete toggle-on-us.svg
pick e4bf1cd Delete trash-icon.png
pick 893f2c2 Delete window-name-focused.svg
pick e3fc71c Delete window-name.svg
pick d5ce012 Delete workspace-shadow.svg

# Rebase 5841c6f..d5ce012 onto 5841c6f (31 command(s))
#
# Commands:
# p, pick = use commit
# r, reword = use commit, but edit the commit message
# e, edit = use commit, but stop for amending
# s, squash = use commit, but meld into previous commit
# f, fixup = like "squash", but discard this commit's log message
# x, exec = run command (the rest of the line) using shell
# d, drop = remove commit
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented out
```
* Now change every but the first `pick` to `s` or `squash`, so it looks like this
``` py
pick 2708032 Add files via upload
squash 23f73b3 Delete calendar-arrow-left.svg
squash a8f358e Delete calendar-arrow-right.svg
squash e54abbf Delete checkbox-off.svg
squash 7522202 Delete checkbox.svg
squash 2111568 Delete cinnamon.css
squash 0e6d45b Delete close-window.svg
squash f1fa5fc Delete close.svg
squash f6e92d2 Delete corner-ripple.png
squash 60d02cd Delete menu-symbolic.svg
squash 349c790 Delete metadata.json
squash 134c0e2 Delete overview-hover.png
squash 924e09d Delete overview.png
squash 84db6a1 Delete panel-button-highlight-narrow.svg
squash c256f3a Delete panel-button-highlight-wide-round.svg
squash 4990e00 Delete panel-button-highlight-wide-round2.svg
squash 17460a9 Delete panel-button-highlight-wide.svg
squash 6e29345 Delete plus.svg
squash a71556d Delete preview.png
squash 0f9ecb2 Delete process-working.svg
squash 44ef09c Delete radiobutton-off.svg
squash 3a099c8 Delete radiobutton.svg
squash ae15420 Delete thumbnail.png
squash 461d35b Delete toggle-off-intl.svg
squash 0593cb2 Delete toggle-off-us.svg
squash 5ac92a6 Delete toggle-on-intl.svg
squash f5f4dbc Delete toggle-on-us.svg
squash e4bf1cd Delete trash-icon.png
squash 893f2c2 Delete window-name-focused.svg
squash e3fc71c Delete window-name.svg
squash d5ce012 Delete workspace-shadow.svg

# Rebase 5841c6f..d5ce012 onto 5841c6f (31 command(s))
#
# Commands:
# p, squash = use commit
# r, reword = use commit, but edit the commit message
# e, edit = use commit, but stop for amending
# s, squash = use commit, but meld into previous commit
# f, fixup = like "squash", but discard this commit's log message
# x, exec = run command (the rest of the line) using shell
# d, drop = remove commit
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented out
```
* Now save the file and close the texteditor. Wait a little bit. Another texteditor open:
```py
# This is a combination of 31 commits.
# The first commit's message is:
Add files via upload
# This is the 2nd commit message:

Delete calendar-arrow-left.svg
# This is the 3rd commit message:

Delete calendar-arrow-right.svg
# This is the 4th commit message:

Delete checkbox-off.svg
# This is the 5th commit message:

Delete checkbox.svg
# This is the 6th commit message:

Delete cinnamon.css
# This is the 7th commit message:

Delete close-window.svg
# This is the 8th commit message:

Delete close.svg
# This is the 9th commit message:

Delete corner-ripple.png
# This is the 10th commit message:

Delete menu-symbolic.svg
# This is the 11th commit message:

Delete metadata.json
# This is the 12th commit message:

Delete overview-hover.png
# This is the 13th commit message:

Delete overview.png
# This is the 14th commit message:

Delete panel-button-highlight-narrow.svg
# This is the 15th commit message:

Delete panel-button-highlight-wide-round.svg
# This is the 16th commit message:

Delete panel-button-highlight-wide-round2.svg
# This is the 17th commit message:

Delete panel-button-highlight-wide.svg
# This is the 18th commit message:

Delete plus.svg
# This is the 19th commit message:

Delete preview.png
# This is the 20th commit message:

Delete process-working.svg
# This is the 21st commit message:

Delete radiobutton-off.svg
# This is the 22nd commit message:

Delete radiobutton.svg
# This is the 23rd commit message:

Delete thumbnail.png
# This is the 24th commit message:

Delete toggle-off-intl.svg
# This is the 25th commit message:

Delete toggle-off-us.svg
# This is the 26th commit message:

Delete toggle-on-intl.svg
# This is the 27th commit message:

Delete toggle-on-us.svg
# This is the 28th commit message:

Delete trash-icon.png
# This is the 29th commit message:

Delete window-name-focused.svg
# This is the 30th commit message:

Delete window-name.svg
# This is the 31st commit message:

Delete workspace-shadow.svg

# Bitte geben Sie eine Commit-Beschreibung für Ihre Änderungen ein. Zeilen,
# die mit '#' beginnen, werden ignoriert, und eine leere Beschreibung
# bricht den Commit ab.
#
# Autor:           Radek71 <radek.otahal@email.cz>
# Datum:            Sat Feb 11 21:57:04 2017 +0100
#
# interaktives Rebase im Gange; auf 5841c6f
# Letzte Kommandos ausgeführt (31 Kommandos ausgeführt):
#    squash e3fc71c Delete window-name.svg
#    squash d5ce012 Delete workspace-shadow.svg
# Keine Kommandos verbleibend.
# Sie editieren gerade einen Commit während eines Rebase von Branch 'Radek' auf '5841c6f'.
#
# zum Commit vorgemerkte Änderungen:
#	umbenannt:      Thunderbolt/files/Thunderbolt/Cinnamon/calendar-arrow-left.svg -> Thunderbolt/files/Thunderbolt/cinnamon/calendar-arrow-left.svg
#	umbenannt:      Thunderbolt/files/Thunderbolt/Cinnamon/calendar-arrow-right.svg -> Thunderbolt/files/Thunderbolt/cinnamon/calendar-arrow-right.svg
#	umbenannt:      Thunderbolt/files/Thunderbolt/Cinnamon/checkbox-off.svg -> Thunderbolt/files/Thunderbolt/cinnamon/checkbox-off.svg
#	umbenannt:      Thunderbolt/files/Thunderbolt/Cinnamon/checkbox.svg -> Thunderbolt/files/Thunderbolt/cinnamon/checkbox.svg
#	umbenannt:      Thunderbolt/files/Thunderbolt/Cinnamon/cinnamon.css -> Thunderbolt/files/Thunderbolt/cinnamon/cinnamon.css
#	umbenannt:      Thunderbolt/files/Thunderbolt/Cinnamon/close-window.svg -> Thunderbolt/files/Thunderbolt/cinnamon/close-window.svg
#	umbenannt:      Thunderbolt/files/Thunderbolt/Cinnamon/close.svg -> Thunderbolt/files/Thunderbolt/cinnamon/close.svg
#	umbenannt:      Thunderbolt/files/Thunderbolt/Cinnamon/corner-ripple.png -> Thunderbolt/files/Thunderbolt/cinnamon/corner-ripple.png
#	umbenannt:      Thunderbolt/files/Thunderbolt/Cinnamon/menu-symbolic.svg -> Thunderbolt/files/Thunderbolt/cinnamon/menu-symbolic.svg
#	umbenannt:      Thunderbolt/files/Thunderbolt/Cinnamon/metadata.json -> Thunderbolt/files/Thunderbolt/cinnamon/metadata.json
#	umbenannt:      Thunderbolt/files/Thunderbolt/Cinnamon/overview-hover.png -> Thunderbolt/files/Thunderbolt/cinnamon/overview-hover.png
#	umbenannt:      Thunderbolt/files/Thunderbolt/Cinnamon/overview.png -> Thunderbolt/files/Thunderbolt/cinnamon/overview.png
#	umbenannt:      Thunderbolt/files/Thunderbolt/Cinnamon/panel-button-highlight-narrow.svg -> Thunderbolt/files/Thunderbolt/cinnamon/panel-button-highlight-narrow.svg
#	umbenannt:      Thunderbolt/files/Thunderbolt/Cinnamon/panel-button-highlight-wide-round.svg -> Thunderbolt/files/Thunderbolt/cinnamon/panel-button-highlight-wide-round.svg
#	umbenannt:      Thunderbolt/files/Thunderbolt/Cinnamon/panel-button-highlight-wide-round2.svg -> Thunderbolt/files/Thunderbolt/cinnamon/panel-button-highlight-wide-round2.svg
#	umbenannt:      Thunderbolt/files/Thunderbolt/Cinnamon/panel-button-highlight-wide.svg -> Thunderbolt/files/Thunderbolt/cinnamon/panel-button-highlight-wide.svg
#	umbenannt:      Thunderbolt/files/Thunderbolt/Cinnamon/plus.svg -> Thunderbolt/files/Thunderbolt/cinnamon/plus.svg
#	umbenannt:      Thunderbolt/files/Thunderbolt/Cinnamon/preview.png -> Thunderbolt/files/Thunderbolt/cinnamon/preview.png
#	umbenannt:      Thunderbolt/files/Thunderbolt/Cinnamon/process-working.svg -> Thunderbolt/files/Thunderbolt/cinnamon/process-working.svg
#	umbenannt:      Thunderbolt/files/Thunderbolt/Cinnamon/radiobutton-off.svg -> Thunderbolt/files/Thunderbolt/cinnamon/radiobutton-off.svg
#	umbenannt:      Thunderbolt/files/Thunderbolt/Cinnamon/radiobutton.svg -> Thunderbolt/files/Thunderbolt/cinnamon/radiobutton.svg
#	umbenannt:      Thunderbolt/files/Thunderbolt/Cinnamon/thumbnail.png -> Thunderbolt/files/Thunderbolt/cinnamon/thumbnail.png
#	umbenannt:      Thunderbolt/files/Thunderbolt/Cinnamon/toggle-off-intl.svg -> Thunderbolt/files/Thunderbolt/cinnamon/toggle-off-intl.svg
#	umbenannt:      Thunderbolt/files/Thunderbolt/Cinnamon/toggle-off-us.svg -> Thunderbolt/files/Thunderbolt/cinnamon/toggle-off-us.svg
#	umbenannt:      Thunderbolt/files/Thunderbolt/Cinnamon/toggle-on-intl.svg -> Thunderbolt/files/Thunderbolt/cinnamon/toggle-on-intl.svg
#	umbenannt:      Thunderbolt/files/Thunderbolt/Cinnamon/toggle-on-us.svg -> Thunderbolt/files/Thunderbolt/cinnamon/toggle-on-us.svg
#	umbenannt:      Thunderbolt/files/Thunderbolt/Cinnamon/trash-icon.png -> Thunderbolt/files/Thunderbolt/cinnamon/trash-icon.png
#	umbenannt:      Thunderbolt/files/Thunderbolt/Cinnamon/window-name-focused.svg -> Thunderbolt/files/Thunderbolt/cinnamon/window-name-focused.svg
#	umbenannt:      Thunderbolt/files/Thunderbolt/Cinnamon/window-name.svg -> Thunderbolt/files/Thunderbolt/cinnamon/window-name.svg
#	umbenannt:      Thunderbolt/files/Thunderbolt/Cinnamon/workspace-shadow.svg -> Thunderbolt/files/Thunderbolt/cinnamon/workspace-shadow.svg
#
```
These are the commit messages. You can change them to something like this:
```py
# This is a combination of 31 commits.
# The first commit's message is:
Thunderbolt: Deleted directory Cinnamon + create directory cinnamon
```
Now save the changes and close the texteditor.
* Now you have to push the changes:
`git push -f`

After that, it should show here on this page only 1 commit.

**Comment by brownsr** [comment]
@Radek71 I've put the directory change through, and the theme is on the spices website now.  It downloads fine, and can be readily installed.  The installation through the theme settings in Cinnamon is still throwing an error, but I suspect that is just some timing issue in how quickly the change propagates.  I'll check tomorrow to be sure.

**Comment by NikoKrause** [comment]
Yeah. Sometimes it takes some hours till the changes arrive on System Settings. I had to learn it the hard way. ;)

**Comment by Radek71** [comment]
@brownsr,
thanks for you help again. I have tested the installation through the theme setting in Cinnamon and seems that everything is OK.

**Pull request closed without merging**
