### PR TITLE
Mint-Yz: a set of 30 Mint-Y-fork themes with different colors (question/issue: how to offer 30 themes all at once!)

### PR DESCRIPTION
**Pull request by SebastJava**
I read your README and associated links and i don’t know how to deal with this. This is a set of 30 themes. They are all the same Mint-Y-fork but in different color variations. They are renamed **Mint-Yz**-Base-COLOR, **Mint-Yz**-Darker-COLOR, and **Mint-Yz**-Darkest-COLOR. So they can be installed alongside the good old Mint-Y sets without replacing them.

This is a whole set of 30 themes and i would appreciate if it could be all downloaded and installed in one or two mouse clicks. All at once. It looks  like this would be possible when downloading from your website and doing a manual install, but not when installing from the Themes module. I did read the file structure should be "UUID/files/UUID", and it seems Cinnamon Themes module would automatically create this conformed file structure if not found.

Sorry, but I find myself in a no-win situation:
* This is more like an issue about the file structure requirements...
* It looks like this could work for manual installs but not for direct Cinnamon Themes automated installs.

Yes, I know, there is a technically compliant method for this: **I should create 30 Pull Requests for 30 different themes.** According to your rules, that is how it should be done. And i could possibly try this soon.

But what would you feel about this? 30 Pull Requests!? Besides, i would much prefer if the whole pack could be downloaded all at once.

So i am just asking for some guidance here, please. What do you feel, what do you think? Thanks in advance.

### CODE REVIEW

**Comment by brownsr** [comment]
I am sorry, I can't action this.  There are over 5000 files to review, that's just not possible I'm afraid.  I would also want to know what these offer over the standard mint-Y themes, as these now come in quite a few colours.

**Comment by SebastJava** [comment]
> I would also want to know what these offer over the standard mint-Y themes

Hi @brownsr 

The answer to your question can be found just by looking at this comparison between the current Mint-Ys and my Mint-Yz:
[Mint-Y-Variations-compare-old.svg](https://github.com/SebastJava/mint-yz-theme/blob/colors/Mint-Y-Colors/compare/Mint-Y-Variations-compare-old.svg) Honestly, I have a strong preference for my version. The complete story can be found in my main [README](https://github.com/SebastJava/mint-yz-theme/blob/colors/README.md).

Frankly speaking, i was quite deceived when i saw Clem moving backwards and doing some compromises by making colors halfway between the old and the new. This collective new version was already not perfectly to my taste. But then it went halfway back. And then Clem just completely reversed everything until LM 20.1, or later, or never. So i decided to have some fun and follow my own track. But it is stealing all my summer time of me. It is much more complicated than you would think at first sight.

We have a dispute over the colors, but apart from that I am still trying to make some positive contributions through other more technical Pull Requests, directly on https://github.com/linuxmint/mint-themes. Moreover, i want to take a look at the other Linux distros, but i think i will just come back and stick to Linux Mint, being convinced it is still the best, under the hood.

Anyway, that was just a "spinoff" from [SebastJava/mint-yz-theme](https://github.com/SebastJava/mint-yz-theme). There is a Debian package there and there will be future update(s), because i am still hesitant over the Mint and MintFresh colors. I am still spending a lot of time trying to find the exact perfect colors.

**Comment by claudiux** [comment]
@SebastJava,

Thank you for all these themes! I installed them using the deb package; did you create a PPA to offer automatic updates?

**Comment by SebastJava** [comment]
@claudiux 
1. Just now, I added an issue section on my repository for future messages. This will be more appropriate than here in this closed PR. Sorry it was not available before.
2. No, i don’t have a PPA yet. I should. It would be much better. There could be updates, later. Honestly, this is... my first Debian package! Don’t be afraid, i am quite confident about my upstream source: the programming and the resulting new themes. Everything got checked and tested several times. But i am just starting to learn about Debian packaging. I should learn about PPAs soon...

**Pull request closed without merging**
