### PR TITLE
Update New-Minty (with joined menus)

### PR DESCRIPTION
**Pull request by germanfr**
Changelog at: https://github.com/germanfr/new-minty/commits/master

### CODE REVIEW

**Comment by clefebvre** [comment]
Hi @germanfr, can you keep the name simple?

"name": "New-Minty (with joined menus)" --> "name": "New-Minty"

**Comment by germanfr** [comment]
Hi. This was intended. As this is a fork of an original work with this minimal modification I made this to state clear the difference. Similar to  the Numix and Numix Transparent case.

**Comment by clefebvre** [comment]
I understand, but we're not providing the original. I don't think you need to deviate from the original name, but if I think you do, please find another name, or edit the existing name. That's not really a name... it's starting to look like a description :)

**Comment by germanfr** [comment]
I'd like to keep that name if possible. It's important for me.

**Comment by clefebvre** [comment]
Ah well, what can I say... it's going to look amateurish on the website and in the system settings.. but I guess you can always change your mind later.

**Pull request merged**
