### PR TITLE
[iOS-X] Create class for use in cinnamenu

### PR DESCRIPTION
**Pull request by fredcw**

### CODE REVIEW

**Comment by brownsr** [comment]
ping @rajatsawant

**Comment by brownsr** [comment]
ping @rajatsawant

**Comment by rajatsawant** [comment]
Hello, please go ahead with the changes. I don’t have mint running to verify right now. Thanks!!

Sent from my iPhone

On 25-Apr-2021, at 11:51 AM, Simon Brown ***@***.***> wrote:

﻿
ping @rajatsawant

**Comment by brownsr** [comment]
@rajatsawant Thanks for the confirmation.

Regards

Simon

**Pull request merged**
