### PR TITLE
Orchidea: Initial creation

### PR DESCRIPTION
**Pull request by Andr35**
Add a new theme called "Orchidea".

### CODE REVIEW

**Comment by brownsr** [comment]
Hmm .. the file specification was under the assumption that there would be just one theme under the files directory.  I'm happy with the themes, but I need to ask around about the upload and download, to see whether this 1:many structure is likely to work or not.

Regards

Simon

**Comment by Andr35** [comment]
Thank you. I read the README.md of this repository and I didn't find any information about the "1:many" topic so I put each variant of the theme in a different `files/UUID` folder thinking that all the content of `files` would be copied in the "theme" folder as a separate theme with  a different name depending on the color. 

However, if this is not possible, I can remove the all the variants and keep only one theme with a single "default" color.

**Comment by brownsr** [comment]
That would be better, and in keeping with the other spices themes.  We had problems with the applets when there were more files than expected in the file structure, and we'd be wary of similar problems with the upload and download routines.

Regards

Simon

**Comment by Andr35** [comment]
I've removed all the theme variants from the `files` folder. Now there is only a folder called "Orchidea-Blue-Dark".

Regards

**Comment by brownsr** [comment]
Can you make the name match ?

**Comment by Andr35** [comment]
Done

**Pull request merged**
