### PR TITLE
Glass Themes: updating versions, removing wheezy, adding new colors.

### PR DESCRIPTION
**Pull request by vlad1777d**
Updated versions of themes, added new color variations, updated scripts according them.

Removed Glass Wheezy from this repository to reduce number of themes to avoid spamming,
but it's still availible at author's repository on GitHub and will be supported.

### CODE REVIEW

**Comment by brownsr** [comment]
Great stuff.   I can't pre-test to see if the renames will cause any problems with the transfer to the web site, so I'll merge and let you know if there are any problems.

**Comment by brownsr** [comment]
Loads up to website fine.  Some of the alignment in a vertical panel could do with attention, panel launchers are coming up quite off-centre, and I think this in turn is causing the popup menu to misalign with the edge of the panel.

**Comment by vlad1777d** [comment]
@brownsr , could you send me screenshots please, I need to know, is problem present only on your machine, or on mine too.
Because I had not seen any big troubles with it.

**Comment by brownsr** [comment]
Here you are @vlad1777d .  Ignore the space under the sound icon, I've seen that in a few places recently , so it is probably a code regression.  You can see that the panel launchers are offset, and also the icons at the top left, though that is more subtle.
screenshot from 2017-05-29 18-06-55

**Comment by vlad1777d** [comment]
@brownsr , thanks. But I have not such problem: [link to image](https://pp.userapi.com/c637930/v637930447/562c1/omNJMTdVqqY.jpg).

Maybe you have some ideas, where to search this problem ?
Because padding for left and right sides, seems, identical.

**Comment by brownsr** [comment]
This sorts it out:

.applet-box.vertical {
	padding-left: 0px;
	padding-right: 0px;
	padding-top: 5px;
	padding-bottom: 5px;
}

**Pull request merged**
