### PR TITLE
Update 0.9.0

### PR DESCRIPTION
**Pull request by Cloweling**
* Change color of music button selection.
* Change of selection style to subcategory menu.
* Change of application selection style in the panel (only applies to the panel below).
* Increase size to notification icons.
* Eliminated the Crismon color and centered only with the color Blue.
* Added and modified the color of the progress bar.

### CODE REVIEW

**Comment by brownsr** [comment]
We spotted a number of themes where the directory names did not match the UUID (unique name), and we changed these.  In this case the CBlak directory will want altering to CBlack.  I presume this is the reason behind the git conflicts.  Could you rename the directory in your local git and re-push, please ?

Regards

Simon

**Comment by Cloweling** [comment]
sorry is my first time doing this, I do not know if I already did it correctly. you tell me and thank you always for your help.

**Comment by Cloweling** [comment]
I do not understand the conflict of cinnamon.css

**Comment by jaszhix** [comment]
Here's some [documentation about merge conflicts](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/) in git. In this case, cinnamon.css has been modified by another contributor on this repo since you last forked the repo and started working on your version of it, so the changes need to be reconciled because git doesn't know how to. 

To prevent this in the future you can [add this repo as a git remote](https://help.github.com/articles/configuring-a-remote-for-a-fork/) and [sync your fork](https://help.github.com/articles/syncing-a-fork/).

**Comment by Cloweling** [comment]
84/5000
Thanks now I have to wait or what do I have to do once the conflict is settled?

**Comment by brownsr** [comment]
well it's now mergeable, no conflicts !  trouble is there's not much there so I doubt that's what you intend.  There's a revised screenshot, and some added lines with margin:auto in the CSS (which causes run-time warnings).

**Comment by Cloweling** [comment]
Sorry, I'm new to all this and I really do not understand this part "added lines with margin:auto in the CSS (which causes run-time warnings)" .

I do not know if you could show me an example.

**Comment by brownsr** [comment]
An example from the css:
`
 .menu-favorites-box {
     margin: auto;
      padding: 5px;
      border: 0px solid #666;
      border-radius: 0px;
...
}
`
the line margin:auto causes run time warnings in use (you can see them in the .xsession-errors file), because Cinnamon does not support 'auto' margin.  They are just warnings, the user will never see the issue, but we removed lines like this from themes.

**Comment by Cloweling** [comment]
Hi, I appreciate your response, I wish you happy holidays and see if today is fine. Thank you very much.

**Pull request merged**
