### PR TITLE
Utnapishtim-Nexus

### PR DESCRIPTION
**Pull request by freemangilgamesh**
sleek theme

### CODE REVIEW

**Comment by brownsr** [comment]
I am struggling to know what to do with this.  I need to scan through the code before merging to ensure there is nothing there that could be a threat to users.  Unfortunately there are zip, tar and binary files there that make that at the very least difficult, and potentially infeasible.

Then there's the fact that the standard file structure ensures that the themes will load and extract through the inbuilt mint loaders.  However I have to presume the tar and gzip files won't work that way.

Then all three themes seem to be in each PR.  That's not a show stopper, could just process one and close the other two.

So I think this needs some more work so that there is a straightforward source code / graphics files PR there to review, and the various zip tar and binary files are removed.

But I do appreciate the work that has clearly gone in to get to know git and to be able to send a PR through.

Regards

Simon

**Comment by freemangilgamesh** [comment]
@brownsr  thank you sir for your pep talk! plz upload them for me. I've been running round in circles trying to figure Github out.

**Comment by JosephMcc** [comment]
@freemangilgamesh You need to understand that we aren't going to upload these for you. We are responsible for seeing to maintenance of every theme here. You are basically saying you aren't going to maintain them. In addition to the problems pointed out to brownsr, your css is very poorly formatted and has some clear errors. That makes the idea of having to fix/maintain them for you even less appealing. If github doesn't work for you there are plenty of other ways to share your themes.

I'd rather not do it, but if you continue to reopen these same declined PR's I will have have to block you from here. If you want to properly fix these then go for it. You can push more commits to these branches even when they are closed. If you get them properly done they can always be reopened.

**Comment by freemangilgamesh** [comment]
stop threatening me! And I don't need you to upload my themes. I was talking to brownsr  bacause he is a nice guy. that's all that it is! and if you have anything against me go ahead and spit it out!

**Pull request closed without merging**
