### PR TITLE
CBlue/CGreen: Improvement for Cinnamon 6.4

### PR DESCRIPTION
**Pull request by Bundy01**
Regards.

### CODE REVIEW

**Comment by rcalixte** [comment]
Your rebase isn't clean. If you try these files, they will fail.

**Comment by Bundy01** [comment]
Sorry,

I used to recover with `git fetch --all` and `git reset --hard ...`.

I tried with `git pull` instead but I don't know this command.

What should I do to remove the conflicts?

**Comment by rcalixte** [comment]
> What should I do to remove the conflicts?

You can review it manually. You can remove the bad rebase commit and try again, etc. etc. If you're not familiar with Git, this is one of the stickier issues but the good news is that there are many well-documented ways to work through it. GitHub has decent documentation for this as well.

**Comment by Bundy01** [comment]
I close this PR.

**Pull request closed without merging**
