### PR TITLE
iOS-X: Initial creation

### PR DESCRIPTION
**Pull request by rajatsawant**

### CODE REVIEW

**Comment by NikoKrause** [comment]
The theme doesn't respect the file structure and it's missing files as info.json, screenshot, etc.

Please read the guideline: https://github.com/linuxmint/cinnamon-spices-themes#file-structure

And clean up the theme, e.g. there's a file, which does not fit to your theme:
https://github.com/rajatsawant/cinnamon-spices-themes/blob/iOS-X1/iOS-X/cinnamon/theme.json

**Comment by rajatsawant** [comment]
Okay, will get back to you!

**Comment by NikoKrause** [comment]
Also note this: https://github.com/linuxmint/cinnamon-spices-themes/issues/221#issuecomment-330680181

**Comment by brownsr** [comment]
The theme looks well put together.  I shall look forward to merging it when it fits the file structure :)

**Comment by rajatsawant** [comment]
@brownsr Thanks!
I have updated the branch, please check. I am sure I have removed the necessary errors.
@NikoKrause

**Comment by brownsr** [comment]
We shall have to see if the website likes the screenshot image file type.  If it does not load there, use a .png.

**Comment by brownsr** [comment]
@rajatsawant   Unfortunately the website definitely does not like the image type of the screenshot, I suggest that you PR a change to .png

Regards

Simon

**Comment by rajatsawant** [comment]
Thank You! @brownsr!

**Pull request merged**
