### PR TITLE
Mint-XP: Restore menu theming in 3.2

### PR DESCRIPTION
**Pull request by brownsr**
Add vertical panel applet-box css
Moved location of the border-image so it does not break vertical panels
Added additional OSD theming

### CODE REVIEW

**Comment by fmcgorenc** [comment]
Hi all. I have updated some of my themes including Mint-XP for Cinnamon 3.2.
They are: [MintOC](http://fmcgorenc.deviantart.com/art/MintOC-659702468), [Modern Mint 2017](http://fmcgorenc.deviantart.com/art/Modern-Mint-2017-659527891), [Mint-XP](http://fmcgorenc.deviantart.com/art/Mint-XP-GTK3-GTK2-and-metacity-included-426641286), [Mint-XP-Metallic](http://fmcgorenc.deviantart.com/art/Mint-XP-Metallic-428961138), [Mint-XP-Homestead](http://fmcgorenc.deviantart.com/art/Mint-XP-Homestead-428960747), [Mane6-for-Cinnamon (6 themes)](http://fmcgorenc.deviantart.com/art/Mane6-for-Cinnamon-516594275) and [Nightmare-Moon-and-Princess-Luna-for-Cinnamon (2 themes)](http://fmcgorenc.deviantart.com/art/Nightmare-Moon-and-Princess-Luna-for-Cinnamon-518142955). If someone wants to upload them to Cinnamon Spices I would very much appreciate it. Thanx

**Comment by NikoKrause** [comment]
You will have to create a pull request to this repository, if you want them to be uploaded on cinnamon spices. 1 Theme - 1 Pull Request

**Comment by fmcgorenc** [comment]
How?

**Comment by fmcgorenc** [comment]
Ok. I've added some repositories to my account ( Note: can't upload Mint-XP themes - says there's too many files) and now what?

**Comment by NikoKrause** [comment]
This won't work. You will have to fork this repository, i.e. linuxmint/cinnamon-spices-themes

**Comment by NikoKrause** [comment]
Also you'll have to use a certain file structure, before you create a pull request.

Read this file before doing anything. If you don't understand something read it twice. Or ask somebody.
https://github.com/linuxmint/cinnamon-spices-themes/blob/master/README.md
And I mean really READ it!

**Comment by fmcgorenc** [comment]
I've read that already many times. btw can UUIDs contain spaces?

**Comment by brownsr** [comment]
@fmcgorenc I'm very happy to help you get your themes up if the current mechanism is proving awkward.  If you can point me towards where I can download them, then I can see to the rest, if that suits you ?

**Comment by fmcgorenc** [comment]
Yes , thank you very much. Here are the themes:  [MintOC](http://fmcgorenc.deviantart.com/art/MintOC-659702468), [Modern Mint 2017](http://fmcgorenc.deviantart.com/art/Modern-Mint-2017-659527891), [Mint-XP](http://fmcgorenc.deviantart.com/art/Mint-XP-GTK3-GTK2-and-metacity-included-426641286), [Mint-XP-Metallic](http://fmcgorenc.deviantart.com/art/Mint-XP-Metallic-428961138), [Mint-XP-Homestead](http://fmcgorenc.deviantart.com/art/Mint-XP-Homestead-428960747), [Mane6-for-Cinnamon (6 themes)](http://fmcgorenc.deviantart.com/art/Mane6-for-Cinnamon-516594275) and [Nightmare-Moon-and-Princess-Luna-for-Cinnamon (2 themes)](http://fmcgorenc.deviantart.com/art/Nightmare-Moon-and-Princess-Luna-for-Cinnamon-518142955).

**Comment by NikoKrause** [comment]
@fmcgorenc
I still suggest you to try it on your own. If you want to update your themes in the future you'll have to learn how to create pull requests.

You'll need to create a fork of this repo, doing changes on your fork and then you'll be able to create pull requests from your fork to this repository.

Here's a small tutorial: https://help.github.com/articles/fork-a-repo/

Feel free to ask, if you get stuck somewhere or need more information.

**Comment by brownsr** [comment]
@fmcgorenc I have uploaded a number of these themes for you, namely MintOC, Modern-Mint-2017, updated Mint-XP (which was already in the repository), Mint-XP-Homestead, and the Nightmare Moon and Princess Luna as the names Blue-Moon and Dark-Moon.  The theme names (UUID) can't contain spaces, so I put dashes in.  I also made a small change to each theme to add .vertical CSS for applet-box so that the alignment in vertical panels looks sensible. If you see anything wrong do tell me, otherwise I will assume it is all fine. The descriptions are very basic as I don't really do HTML. Barring any immediate changes, from here on it it is over to you to make any further changes - by sending in a pull request, or for simple changes there is a limited facility to make direct edits on github if the process of forking, cloning and sending in pull requests is unfamiliar to you.  I have not loaded the mane6 themes as the 6-way image would be difficult for people to use on the spices website as the theme names (Honesty etc.) would be hard to associate with the appropriate sub-image. I am not offering to load these if you provide separate images I am afraid - I need to move on to do some other work now.  Regards.  Simon

**Comment by fmcgorenc** [comment]
Ok, thank you for all your help. Later. Frank

**Pull request merged**
