### PR TITLE
7 themes: nonexistent github user names and license keys

### PR DESCRIPTION
**Pull request by NikoKrause**
The authors @abnvolk @debimint @kessaras @mztrdlk @thorin0815 are not GitHub usernames. Therefore mention them as `original_author` and set `author` to `none`

### CODE REVIEW

**Comment by NikoKrause** [comment]
@brownsr Do you know if Frankula Wolfenstein (Spider-Void theme) has a GitHub account? I found the Google+ site, but no mention of his GitHub username.

**Comment by brownsr** [comment]
@NikoKrause Not as far as I know, I've been acting as Github proxy for a few theme authors.

**Comment by NikoKrause** [comment]
The goal is to have the github usernames of the authors, so people know, who to creator is, who to contact when opening an issue and also the name of the author (on the spices website) should be a link to the author's GitHub page.

**Comment by NikoKrause** [comment]
added license keys for those themes with license files in it

**Comment by NikoKrause** [comment]
I shortened the descriptions in the info.json.

This can be merged now. Removed the WIP

**Pull request merged**
