### PR TITLE
Add Railway theme

### PR DESCRIPTION
**Pull request by germanfr**
Changelog at: https://github.com/germanfr/railway-cinnamon/commits/master

### CODE REVIEW

**Comment by germanfr** [comment]
I have a question. What's the difference between theme.json and info.json?

**Comment by brownsr** [comment]
only the info.json in the UUID/info.json directory is needed.  Without that file the script that sends it off to the spices website will not be able to process it.  Can you add it to this PR ?  I can't merge it without it.

**Comment by germanfr** [comment]
@brownsr ok I'll do. 
Is there any recognized field where I can specify an url/website/repo like in the old spices?

**Comment by brownsr** [comment]
I don't think so.  The website button on the spices site just links back to the github repository, for that specific theme.  I've been using the description text in the info.json file, or I guess you could use the optional README.md

**Comment by germanfr** [comment]
Ok, I guess it's done.

**Comment by germanfr** [comment]
@brownsr for some reason it says _"This theme is missing an info.json"_. Did I do anything wrong?

**Comment by Odyseus** [comment]
Hello, everybody.

@germanfr: The HTML code in the description key inside the info.json file isn't escaped. You have to escape all instances of **"** to **\\"** or use single quotes.

**Comment by germanfr** [comment]
Thanks @Odyseus, I totally forgot that.

**Pull request merged**
