### PR TITLE
Adapta Themes - Initial Commit

### PR DESCRIPTION
**Pull request by smurphos**
Builds of the Adapta theme with minor modifications from the original source and an intention to maintain with ongoing GTK3.18 support as discussed at #397 

Is the authorship info.json appropriate? I've listed myself as the author with the developer of Adapta listed as the original author.

### CODE REVIEW

**Comment by JosephMcc** [comment]
If you are keeping the same name as the original, it's probably good form to let the original dev know if you haven't.

**Comment by brownsr** [comment]
There are 2956 files here.  Be aware that I will visually scan all source code files to check that there is nothing overtly worrying there, so that will take me some time, and with this many files it's not the sort of thing I can squeeze in between other things readily.  So please have reasonable expectations of review and merge times.

Regards

Simon

**Comment by smurphos** [comment]
Sorry Simon, yes there are a lot of assets.

I've made @tista500 aware of the intention via https://github.com/adapta-project/adapta-gtk-theme/issues/666

**Comment by brownsr** [comment]
OK. I'm content.  It all seems to work, and there was nothing of concern on a visual scan.

However ... this is far too big.  It's taken me three hours just to give it a coarse visual scan.  Github and my browser were struggling to serve it to me, and I can't recollect ever using that much memory on this PC.

So, please, anything similar in the future, just one theme per PR please.

As you plan to maintain at regular intervals I would recommend you consider filtering stuff out.  There are quite a few lines meant for budgie in the gtk css for example, that won't be likely to be relevant in a mint context or or in a cinnamon specific context.  The 'all css on a single line' style should make filtering stuff out straightforward.

Regards

Simon

**Comment by smurphos** [comment]
Thanks Simon. Comments noted and absorbed. Wrists slapped. I didn't mean to ruin your day ;-). The irrelevant third party app theming I'll review and comment out in the source scss before the next update - there is indeed a big budgie section. I will also stick to the one theme per PR rule in future as-well.

**Pull request merged**
