### PR TITLE
Added The Sentinel theme

### PR DESCRIPTION
**Pull request by j-nolan**
This is a theme I customized for myself and have been using since more than a year and thought some other people might enjoy it.

### CODE REVIEW

**Comment by brownsr** [comment]
Thanks very much for submitting this @j-nolan .  There's a couple of changes that will have to be made, straightforward, and only one I think absolutely has to be made straightaway.  Generally the theme comes up fine under Cinnamon 3.2, there's a couple of minor alignment issues, but they are not that significant.  The exception is that the menu CSS does not match the latest, and so there is some partial fallback to the default cinnamon menu going on.  A new .menu class needs to be created, basically using the relevant bits of .popup-menu and .popup-menu-boxpointer.  If you take a look at other themes you will quickly see what is going on.  So the question becomes how do we proceed.  As your github site shows that you know your way around git, then I would suggest that you push a new commit through with a revised CSS once you have it working.  I will then merge or squash-merge as appropriate.  If you could also add a suitable applet-box.vertical then that will stop applets looking rather piled on top of each other in a vertical panel then that would be good.  The only other issue I notice is that the window list icons come up slightly off-centre in a vertical panel, but that's not offset enough to look odd.  I look forward to seeing your revisions, and to being able to merge this new theme.

**Comment by j-nolan** [comment]
Hello @brownsr, thank you very much for testing my PR and providing such detailed explanations.

I am running Cinnamon 2.8.8 on Mint 17.3. I will need to update to make these changes. I imagine the easiest way will be to start from a fresh 18.1 installation. I will do this on a weekend to avoid messing with my working setup.

I definitely want to make these revisions but I might not have time these two upcoming weekends. I suggest you close the PR and I will come back to you when I'm done.

**Comment by brownsr** [comment]
@j-nolan No rush, it can wait until you're ready :)

**Comment by clefebvre** [comment]
Closing for now. Please reopen when appropriate.

**Pull request closed without merging**
