### PR TITLE
Add new theme Warthog

### PR DESCRIPTION
**Pull request by Radek71**
[Warthog.zip](https://github.com/linuxmint/cinnamon-spices-themes/files/2729916/Warthog.zip)

### CODE REVIEW

**Comment by claudiux** [comment]
Nice work!
So that the icons of GWL are not crushed, the panel must have a size of 45 pixels.

**Comment by brownsr** [comment]
As far as I can see the zip file looks OK in file structure, however what is here as a git pull request appears to have got mangled, and is coming across as a set of changes to the Thunderbolt theme, and as you can see from the note just above it has conflicts that would need to be resolved.  I suggest creating a new branch in your repository, checking it out, and then copying the files in from somewhere you have stashed them from your zip file.  Then the normal add, commit, and pushing of the branch should give me something I can work on.

Regards

Simon

**Comment by brownsr** [comment]
not quite there on the git side I am afraid, what is actually coming through is a minor padding change on one element of your Thunderbolt theme. See the 'files changed' tab above.

I recommend getting what you want into an entirely new branch of your repository and pushing that.  I put a simple git 'how to' in the readme of this repository if that helps.

Regards

Simon

**Comment by brownsr** [comment]
So ... I pulled your other PR, but I had not spotted that there was another Thunderbolt change tied up in there, so I have had to revert it.

You need to send me a PR that only has the new Warthog theme in there, and that does not have Thunderbolt changes mixed into it.  If you have a messed up git repository, the simplest thing for you is probably to remove it (saving any files you need locally, outside the git repository) entirely, and then to create a new clone from the main mint repository.  Then branch, checkout the branch, copy in your files, inspect and test as appropriate, commit, and push the branch. 

Regards

Simon

**Comment by brownsr** [comment]
No activity, closing

**Pull request closed without merging**
