### PR TITLE
Added CBlack-Remix

### PR DESCRIPTION
**Pull request by Vanov**

### CODE REVIEW

**Comment by brownsr** [comment]
Getting there ...  UUIDs are mixed up a bit, so your top level is CBlack-Remix, but there's a file directory under there called CBlack.  That will confuse the loaders, both want to be the same name.

**Comment by Vanov** [comment]
cock

**Comment by Vanov** [comment]
Should be fixed now.

**Comment by brownsr** [comment]
Still not there on the file structure I'm afraid.    The cinnamon specific files need to be under a directory called 'cinnamon' :  e.g  UUID/files/UUID/cinnamon/cinnamon.css

**Comment by NikoKrause** [comment]
Please add the `license` of your theme to the `info.json` file as it is done in other themes: https://github.com/linuxmint/cinnamon-spices-themes/search?l=JSON&q=license&type=

**Pull request closed without merging**
