### PR TITLE
Added Jade-1 theme

### PR DESCRIPTION
**Pull request by madmaxms**
new theme Jade-1

### CODE REVIEW

**Comment by brownsr** [comment]
Thanks @madmaxms it's mergeable as it stands, but there's a few minor changes for Cinnamon 3.4 that will want  making at some time (see the 'aide memoire' issue), and there's no point having a folder with gnome-shell theming in.  But there's nothing that would stop me merging it.  So what would you prefer - merge and clean up a few minor issues afterwards, or you adjust first before merging ?

**Comment by madmaxms** [comment]
Hey, no problem, I'll fix the issue first and do a second pull request.

Am 21. Mai 2017 15:43:56 MESZ schrieb Simon Brown <notifications@github.com>:
>Thanks @madmaxms it's mergeable as it stands, but there's a few minor
>changes for Cinnamon 3.4 that will want  making at some time (see the
>'aide memoire' issue), and there's no point having a folder with
>gnome-shell theming in.  But there's nothing that would stop me merging
>it.  So what would you prefer - merge and clean up a few minor issues
>afterwards, or you adjust first before merging ?  
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/linuxmint/cinnamon-spices-themes/pull/168#issuecomment-302937613

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by brownsr** [comment]
@madmaxms Almost ... I will change that bit in the issue, as it's not as clear as I intended.  I suggest just adding the spacing into the (horizontal) applet-box code.  So currently it is:

.applet-box {
    padding-left: 3px;
    padding-right: 3px;
    color: #ccc;
    text-shadow: black 0px 0px 2px;
}

just put the    spacing: 3px;            into this bit of css.       

Don't bother with:

.panel-top .applet-box,
.panel-bottom .applet-box {
spacing: 3px;
}

Thanks

Simon

**Comment by madmaxms** [comment]
ok, it's done

**Comment by brownsr** [comment]
@madmaxms I'll merge, and check out if that spacing works.  Not quite what I intended to convey, but it may be fine.

**Pull request merged**
