### PR TITLE
Chinvat

### PR DESCRIPTION
**Pull request by freemangilgamesh**
theme based on  qob  by archqob   https://cinnamon-spices.linuxmint.com/themes/view/qob

### CODE REVIEW

**Comment by freemangilgamesh** [comment]
What's wrong Linux Mint github guys!!!

I have been trying to upload themes and you kept declining theme. My last theme is based on a theme you just aploaded to Cinnamon "qob" https://cinnamon-spices.linuxmint.com/themes/view/qob this theme gets accepted but mine not and you gave me errors you are responsible for!!!!!!!!!!!!

**Comment by brownsr** [comment]
Hi @freemangilgamesh 

There are still .zip and .tar files embedded in here that I am afraid I can't take.  For the reason I gave last time - hard to review to ensure they don't contain any malicious code, and primarily because the loaders won't process them.  
There's multiple themes here, which does not help.  It makes it a lot easier to review PRs when there is just one theme in each one, for sheer volume of code to look through if nothing else.  I scan each file visually, so if you can give me one theme at a time in a PR it would be appreciated.  And yes, I do get multiple themes in PRs from other people but these tend to be colour variations from automated scripts, so a little simpler for me to review.  chinvat looked fine from a visual scan, but I can't move on to the next step of checking while all the zips and tars from MGSE-Unity are in the same PR.  This next step would be to load the theme myself and check it functions.

So if you could please get rid of those zips and tars and give me one theme per PR it would be much appreciated, and it will make checking much faster.  I note that you are PRing from your master branch.  I'd recommend one theme in a separate branch, as it avoids unintended side effects like getting different themes in the same PR, and I jotted down a few git tips in the main readme which might help.

Regards

Simon

**Comment by freemangilgamesh** [comment]
thank you simon but how can I delete these zip files?

**Comment by brownsr** [comment]
I would suggest creating a branch per theme in git, then just don't copy the .zip files there in the first place.  For example, assuming you have the theme set up in a suitable 
directory structure outside git

git branch ABranchNameOfYourChoice
git checkout ABranchNameOfYourChoice
[copy all your theme files in]
git add [your theme files using wildcards as appropriate]
git commit -m "My New Theme: initial creation"
git push origin ABranchNameOfYourChoice
[assuming you started by forking cinnamon-spices-themes to your own github account]
[create pull request from your github account]

**Comment by freemangilgamesh** [comment]
i give up man!! thanks bro!

**Comment by brownsr** [comment]
@freemangilgamesh Git can be frustrating at first, but you are not far off.  You have got all your themes into git, I can see you have created a number of commits, and you have got a PR submitted.  That's basically all you need.  Just do it in branches so all the themes don't come through on top of each other, and don't put those .zips and .tars into the directories that you copy in to git.

I put a simple git tutorial into the readme at the start of this repository.  It doesn't say much more than I did in the comment above, but the formatting is a bit better and it's probably easier to read.  You might like to look that over.

Regards

Simon

**Comment by freemangilgamesh** [comment]
maany thanks bro!! i removed all these .zip files check now!!

**Comment by freemangilgamesh** [comment]
Did my theme get accepted bro?

**Comment by brownsr** [comment]
Good, no more tars or zips.  I'll start working through the code.

**Comment by brownsr** [comment]
There's quite a few problems, but nothing that actually breaks things.  

There's a couple of lines missing the semi colon on the end in the .css - look at the Codacy report above to see where. These are in Chinvat.

I saw quite a few issues with vertical panels, I guess you don't use these so you might not have tested them out.  Things such as applets with symbolic icons (like the power, network sound applets) stacked above each other without spacing. Things like margin in the panel launchers squashing the icons into a rectangular shape, and offset icons in the window list. Things like low opacity so all the theme panels tended to look like minimally tinted glass if vertical, and changing between themes looked very samey. 
None of these are terribly hard to fix, but I suggest you work through and clean these up.

Then I saw cases where the screenshot and the thumbnail looked quite different.  That's likely to confuse people.

Generally I found it hard to tell one theme from the other from the screenshots.  I wasn't entirely convinced that the screenshots had not got inadvertently cloned.  And I suggest a little more description so the user will have an idea what they are getting.

But none of these are sufficient in my opinion to stop me merging these.  However I would like you to sort these issues out once I have merged them.  I am sure you would want your themes to look their best anyway.  As a bit of an incentive you might like to know I will be reviewing the set of themes after mint 19 is released, and will be pruning out themes with obvious issues, those that seem very similar to others, etc.  

So well done for getting this far, and I look forward to seeing the remaining issues resolved by later PRs.  One per theme, please.

Regards

Simon

**Comment by freemangilgamesh** [comment]
many thanks man you are the best!!

**Comment by freemangilgamesh** [comment]
I go through my css file now and check them for errors! thanks bro!

**Comment by freemangilgamesh** [comment]
you can delete these 4 themes bro:
1. Chinvat: https://cinnamon-spices.linuxmint.com/themes/view/Chinvat
2. Nexus: https://cinnamon-spices.linuxmint.com/themes/view/Nexus
3. OSX: https://cinnamon-spices.linuxmint.com/themes/view/OSX
4. Utnapishtim-Nexus: https://cinnamon-spices.linuxmint.com/themes/view/Utnapishtim-Nexus

these are variants of MGSE-Unity and Utnapishtim-Sleek

**Pull request merged**
