### PR TITLE
Mint-XY-Greybird-Blue updated README

### PR DESCRIPTION
**Pull request by Odyseus**

### CODE REVIEW

**Comment by brownsr** [comment]
Would it be possible to make your note straightforwardly factual? Something like:

I would like any questions about this theme logged at ...... so that I am notified when this happens

**Comment by Odyseus** [comment]
Hello, @brownsr.

> Would it be possible to make your note straightforwardly factual?

No. That paragraph says exactly (straightforwardly so) **what** to do and **why** it needs to be done.

**Comment by brownsr** [comment]
it's factual certainly, it's just it reads as if written in anger.  I hope that's not what is intended.

**Comment by jaszhix** [comment]
Following up here since it applies to all the xlets. Maybe the stuff about the Spices website could be toned down. Unless you're open to changing all of these again when notifications are added to comments. The spices website is still in active development.

**Comment by Odyseus** [comment]
Hello, everybody.

@jaszhix: Like I already said...

> That paragraph says exactly (straightforwardly so) what to do and why it needs to be done.

...no muss, no fuss.

> Unless you're open to changing all of these again when notifications are added to comments.

But of course, that goes without saying. If and when that happens.

**Pull request merged**
