### PR TITLE
Themes by @germanfr

### PR DESCRIPTION
**Pull request by NikoKrause**
Cleanup info.json files
See https://github.com/linuxmint/cinnamon-spices-themes/issues/252

@germanfr

### CODE REVIEW

**Comment by germanfr** [comment]
Please see #264.

**Comment by NikoKrause** [comment]
That's only the Railway theme. 
Will you change New Minty too?
If so, then I'll close this. Just wanted to help out.

**Comment by germanfr** [comment]
Yes, I will. I have to add some more tweaks to it.

**Comment by NikoKrause** [comment]
Cool

**Pull request closed without merging**
